DROP TABLE IF EXISTS account
DROP TABLE IF EXISTS transactions;

CREATE TABLE account(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    acct_name TEXT UNIQUE NOT NULL,
    acct_pass TEXT NOT NULL,
    balance REAL NOT NULL DEFAULT 0.00
);

CREATE TABLE transactions(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id INTEGER NOT NULL,
    type TEXT NOT NULL,
    amount REAL NOT NULL DEFAULT 0.00,
    occurred TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES account (id)
)